library(httr)
library(jsonlite)
library(readr)

# Function to configure the API call
configure_api_call <- function(api_token_path, annotation_set_id, pixel_width = 1360, pixel_height = 1024) {
  # Load API token
  api_token <- read_delim(api_token_path, delim = " ", col_names = FALSE) %>% pull()
  
  # Set base URL for SQ+
  base_url <- "https://squidle.org/api/annotation_set/"
  
  # Set annotation individual annotation set ID
  ID <- paste0(annotation_set_id, "/export?")
  
  # Set pixel dimensions
  pixels <- paste0("&pixel_width=", pixel_width, "&pixel_height=", pixel_height)
  
  # Set the remaining filters for export
  template <- 'template=dataframe.json&disposition=attachment&include_columns=["label.id","label.uuid","label.name","label.lineage_names","comment","needs_review","tag_names","updated_at","point.id","point.x","point.y","point.t","point.data","point.pixels","point.is_targeted","point.media.id","point.media.key","point.media.path_best","point.pose.timestamp","point.pose.lat","point.pose.lon","point.pose.alt","point.pose.dep","point.media.deployment.key","point.media.deployment.campaign.key","point.media.deployment.name","point.media.deployment.campaign.name"]&'
  
  filters <- 'f={"operations":[{"module":"pandas","method":"json_normalize"},{"method":"sort_index","kwargs":{"axis":1}}]}&q={"filters":[]} &translate={"vocab_registry_keys":["worms","caab","catami"]}'
  
  # Generate the full URL
  full_url <- paste0(base_url, ID, template, filters, pixels)
  
  list(full_url = full_url, api_token = api_token)
}

# Function to run the JSON call
run_json_call <- function(full_url, api_token) {
  # Hit the API to get data
  res <- GET(URLencode(full_url), add_headers("X-auth-token" = api_token))
  json <- jsonlite::fromJSON(content(res, 'text'), simplifyVector = TRUE, flatten = TRUE)
  
  # Poll request
  host <- "https://squidle.org"
  res2 <- NULL
  
  while (TRUE) {
    res_raw <- GET(URLencode(paste0(host, json$status_url)), add_headers("X-auth-token" = api_token))
    res1 <- jsonlite::fromJSON(content(res_raw, 'text'), simplifyVector = TRUE, flatten = TRUE)
    
    if (res1$result_available | res1$status == "done") {
      res2 <- GET(URLencode(paste0(host, json$result_url)), add_headers("X-auth-token" = api_token))
      break
    } else if (res1$status == "error") {
      break
    }
    
    Sys.sleep(1)
    # Add progress/status bar as needed
  }
  
  # Flatten JSON results into a dataframe
  results_json <- jsonlite::fromJSON(content(res2, 'text'), simplifyVector = TRUE, flatten = TRUE)
  
  return(results_json)
}


# Function to run the JSON call with a progress/status bar
run_json_call <- function(full_url, api_token) {
  # Hit the API to get data
  res <- GET(URLencode(full_url), add_headers("X-auth-token" = api_token))
  json <- jsonlite::fromJSON(content(res, 'text'), simplifyVector = TRUE, flatten = TRUE)
  
  # Poll request
  host <- "https://squidle.org"
  res2 <- NULL
  
  # Initialize progress bar
  pb <- txtProgressBar(min = 0, max = 100, style = 3)
  progress <- 0
  
  while (TRUE) {
    res_raw <- GET(URLencode(paste0(host, json$status_url)), add_headers("X-auth-token" = api_token))
    res1 <- jsonlite::fromJSON(content(res_raw, 'text'), simplifyVector = TRUE, flatten = TRUE)
    
    if (res1$result_available | res1$status == "done") {
      res2 <- GET(URLencode(paste0(host, json$result_url)), add_headers("X-auth-token" = api_token))
      setTxtProgressBar(pb, 100)  # Set progress to 100% when done ## to get polling correct
      break
    } else if (res1$status == "error") {
      close(pb)  # Close progress bar on error
      stop("Error in processing the request.")
    }
    
    progress <- min(progress + 10, 99)  # Increment progress but do not exceed 99%
    setTxtProgressBar(pb, progress)
    
    Sys.sleep(1)
  }
  
  close(pb)  # Close progress bar
  
  # Flatten JSON results into a dataframe
  results_json <- jsonlite::fromJSON(content(res2, 'text'), simplifyVector = TRUE, flatten = TRUE)
  
  return(results_json)
}


# Step 1: Configure the API Call
config <- configure_api_call(
  api_token_path = "C:/Users/jmonk1/Dropbox/12_Code/SQUIDLE_API_TOKEN.txt",  # Path to your API token
  annotation_set_id = "13567",  # Annotation set ID you want to extract
  pixel_width = 1360,  # Width of the image
  pixel_height = 1024  # Height of the image
)

# Step 2: Run the JSON Call
results <- run_json_call(
  full_url = config$full_url,  # The full URL generated by configure_api_call
  api_token = config$api_token  # The API token loaded by configure_api_call
)

# Step 3: View the Results
print(results)

# 
# 
# 
# {
#   "completed_at": "2024-08-29T00:30:35.340787",
#   "message": "",
#   "progress": {
#     "data.query_to_dicts": {
#       "duration": 9.617865800857544,
#       "iteration": 1000,
#       "iteration_count": 1000,
#       "status": "done"
#     },
#     "pandas.json_normalize": {
#       "duration": 0.06731438636779785,
#       "iteration": 1,
#       "iteration_count": 1,
#       "status": "done"
#     },
#     "self.sort_index": {
#       "duration": 0.004616737365722656,
#       "iteration": 1,
#       "iteration_count": 1,
#       "status": "done"
#     }
#   },
#   "queued_at": "2024-08-29T00:30:25.470728",
#   "result_available": true,
#   "started_at": "2024-08-29T00:30:25.495202",
#   "status": "done",
#   "user_id": "167"
# }

